### ISSUE TITLE
upgrade to polkadot-v0.9.9

### ISSUE THREAD

**Issue by DICO-TEAM** [DICO-TEAM/dico-chain#11]

**Comment by cj1afs** [comment]
polkadot is v0.9.10 now.

**Comment by DICO-TEAM** [comment]
upgrade to latest polkadot version.

**Comment by DICO-TEAM** [comment]
polkadot release: https://github.com/paritytech/polkadot/releases

**Comment by cj1afs** [comment]
polkadot-version

https://github.com/paritytech/polkadot/blob/289d9fc694dd60a331a1a8739c5fbe36c261d5a7/node/client/Cargo.toml#L1-L5
