### ISSUE TITLE
Pick a better name?

### ISSUE THREAD

**Issue by gilescope** [DICO-TEAM/dico-chain#177]
Disco would be fine. DICO is just not a good name when pronounced in English. (Apologies to anyone called Dick out there - no offense intended.)

I can't see that the current name would have the broad appeal that you are seeking. Integretee renamed themselves as prior art of renames happening.

**Comment by cj1afs** [comment]
Hi, @gilescope Thank you for your attention, the `D-I-C-O` is just a tag.
