### ISSUE TITLE
getPrice calculation error

### ISSUE THREAD

**Issue by yytomives** [DICO-TEAM/dico-chain#62]
**Description**
Incorrect calculation of transaction pair price,The result of getPrice is also incorrect

**Solutions**
Calculation of the price of an asset in a pair, taking into account the precision of the individual assets

**Comment by Kavenone** [comment]
> **Description**
> Incorrect calculation of transaction pair price,The result of getPrice is also incorrect
> 
> **Solutions**
> Calculation of the price of an asset in a pair, taking into account the precision of the individual assets

his was caused by a misjudgment of the expiration of the ICO, which has been resolved

**Comment by Kavenone** [comment]
it was caused by a misjudgment of the expiration of the ICO, which has been resolved
